//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaJuanDavidMoreno.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETER_ITEMS
    {
        public int ID_PITEMS { get; set; }
        public int ID_PARAMETER { get; set; }
        public string TYPE_DATA { get; set; }
        public string VALUE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime LAST_MODIFICATION { get; set; }
        public Nullable<int> ID_USER { get; set; }
    
        public virtual PARAMETER PARAMETER { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
