//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int ID_USER { get; set; }
        public string NAME { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public System.DateTime? DATE_CREATE { get; set; }
        public System.DateTime? LAST_MODIFIED { get; set; }
    }
}
