//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestJDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.PARAMETERS_GENERAL = new HashSet<PARAMETERS_GENERAL>();
        }
    
        public int ID_USERS { get; set; }
        public string NAME { get; set; }
        public string LAST_NAME { get; set; }
        public int DOCUMENT { get; set; }
    
        public virtual ICollection<PARAMETERS_GENERAL> PARAMETERS_GENERAL { get; set; }
    }
}
